games/urls.py
from django.urls import path
from members.views import profile_page
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'games'

urlpatterns = [
	path('add_game/', views.add_game, name='add_game'),
	path('add_game/<int:game_id>', views.add_game, name='add_game_with_id'),
	path('game_list/', views.game_list, name='game_list'),
	path('game_create/', views.game_create, name='game_create'),
	path('game_create/<int:suggestion_id>', views.game_create, name='game_create_with_suggestion'),
	path('game_suggestions/', views.game_suggestions, name='game_suggestions'),
	path('suggestion_create/', views.suggestion_create, name='suggestion_create'),
	path('remove_game/', views.remove_game, name='remove_game'),
	path('update_game_status/', views.update_game_status, name='update_game_status'),
	path('game/<int:game_id>/', views.game_detail, name='game_detail'),
	path('game/<int:game_id>/edit', views.edit_game, name='edit_game'),
	path('game/<int:game_id>/rate_game/<int:rating>', views.rate_game, name='rate_game'),
]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
	path('login_user', views.login_user, name='login'),
	path('logout_user', views.logout_user, name='logout'),
	path('signup_user', views.signup_user, name='signup'),
	path('profile/<str:username>', views.profile_page, name='profile'),
	path('social', views.social, name='social'),
	path('aboutus', views.aboutus, name='aboutus'),
]

pandalibrary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('games/', include('games.urls')),
    path('', index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/authentication/aboutus.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
    <div class="container text-center">
    <div class="row" style="padding-top: 10px; margin-top: 3%; text-align: left; border-bottom: 1px solid black; ">
        <div class="col">
            <h2>About Us</h2>
        </div>
    </div>
</div>
    <p>This project is the final Django project for the Web Programming course at Acibadem University.</p>
    <p>The site is developed by Yusuf Eren Arı, Vefa Mert Toker, and Ammar Yasir Bayır.</p>
</div>
{% endblock %}

templates/authentication/login.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">
    <form action="" method=POST>
        {% csrf_token %}
    <div class="container text-center">
            <div class="row" style="padding-top: 10px; margin-top: 3%; text-align: left; border-bottom: 1px solid black; ">
                <div class="col">
                    <h1>Log in</h1>
                </div>
            </div>
    </div>
<div class="container" style="padding: 2%">
  <div class="mb-3">
    <label for="InputUsername" class="form-label">Username</label>
    <input type="text" class="form-control" name="username" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="InputPassword" class="form-label">Password</label>
    <input type="password" class="form-control" name="password">
  </div>
  <button type="submit" class="btn btn-primary">Log in</button>
  </div>
    </form>
{% endblock %}

templates/authentication/profile.html
{% extends 'index.html' %}

{% block additional_styles %}
    <style>
    .columns-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .column {
        flex: 1;
        margin: 10px;
    }

    .game {
        border: 1px solid #000;
        padding: 10px;
        margin: 10px 0;
        text-align: center;
        box-shadow: 0 2px 5px rgba(0,0,0,0.3);
        position: relative;
    }
    .game:hover {
        box-shadow: 0 5px 15px rgba(0,0,0,0.5);
    }

    .delete-game {
        position: absolute;
        top: 10px;
        right: 10px;
        border: none;
        background: none;
    }

    </style>
{% endblock %}

{% block content %}
    {% if user.is_authenticated and request.user.username == user.username %}
        <div class="container text-center">
            <div class="row" style="padding-top: 10px; margin-top: 3%; text-align: left; border-bottom: 1px solid black; ">
                <div class="col">
                    <h2>Your Profile</h2>
                </div>
            </div>
        </div>
    {% else %}
    <div class="container text-center">
        <div class="row" style="padding-top: 10px; margin-top: 3%; text-align: left; border-bottom: 1px solid black; ">
            <div class="col">
                <h2>{{ user.username }}'s Profile</h2>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="container text-center" style="margin-top: 35px; padding-bottom: 20px; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);">
        <form method="post">
            {% csrf_token %}
        </form>
        <div class="columns-container">
            <div id="playing" class="column">
                <h3>Playing</h3>
                {% for user_game in playing_games %}
                <div class="game" data-id="{{ user_game.game.id }}">
                    <a href="{% url 'games:game_detail' user_game.game_id %}" style="color: inherit; text-decoration: none; align-items: center;">
                    {{ user_game.game.title }}
                    {% if user.is_authenticated and request.user.username == user.username %}
                        <button class="delete-game">&#x2715;</button>
                    {% endif %}
                    </a>
                </div>
                {% endfor %}
            </div>

            <div id="will_play" class="column">
                <h3>Will Play</h3>
                {% for user_game in will_play_games %}
                <div class="game" data-id="{{ user_game.game.id }}">
                    <a href="{% url 'games:game_detail' user_game.game_id %}" style="color: inherit; text-decoration: none; align-items: center;">
                        {{ user_game.game.title }}
                        {% if user.is_authenticated and request.user.username == user.username %}
                            <button class="delete-game">&#x2715;</button>
                        {% endif %}
                    </a>
                </div>
                {% endfor %}
            </div>

            <div id="finished" class="column">
                <h3>Finished</h3>
                {% for user_game in finished_games %}
                <div class="game" data-id="{{ user_game.game.id }}">
                    <a href="{% url 'games:game_detail' user_game.game_id %}" style="color: inherit; text-decoration: none; align-items: center;">
                    {{ user_game.game.title }}
                    {% if user.is_authenticated and request.user.username == user.username %}
                        <button class="delete-game">&#x2715;</button>
                    </a>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
        {% if user.is_authenticated and request.user.username == user.username %}
        <a href="{% url 'games:add_game' %}" class="btn btn-primary">Add Game</a>
        {% endif %}
    </div>

{% endblock %}

{% block additional_scripts %}
    {% if user.is_authenticated and request.user.username == user.username %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script>
        $(function() {
            function makeDraggable(element) {
                element.draggable({
                    revert: "invalid",
                    helper: function() {
                        // Clone the entire game element, including the delete button
                        return $(this).clone();
                    }
                });
            }

            makeDraggable($(".game"));

            $(".column").droppable({
            accept: ".game",
            drop: function(event, ui) {
                var game_id = ui.helper.data('id');
                var status = $(this).attr('id');
                var droppableElement = $(this);

                // Send AJAX request to server to update game status
                $.ajax({
                    url: '{% url 'games:update_game_status' %}',  // replace with the actual URL of your view
                    method: 'POST',
                    data: {
                        'game_id': game_id,
                        'status': status,
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                    },
                    success: function(data) {
                        // Create a new clone of the original game
                        var newGame = ui.draggable.clone();

                        // Append the new game to the column
                        newGame.appendTo(droppableElement);

                        // Make the new game draggable
                        makeDraggable(newGame);

                        // Remove the original game from its original column
                        ui.draggable.remove();
                    }
                });
            }
        });

            // Attach a click event handler to the existing delete buttons
            $('.delete-game').click(function() {
                var game_id = $(this).parent().data('id');

                $.ajax({
                    url: '{% url 'games:remove_game' %}',  // replace with the actual URL of your delete view
                    method: 'POST',
                    data: {
                        'game_id': game_id,
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                    },
                    success: function(data) {
                        // Remove the game element from the DOM
                        $(this).parent().remove();
                    }.bind(this)
                });
            });
            // Attach a click event handler to the existing and future delete buttons
            $(document).on('click', '.delete-game', function() {
                var game_id = $(this).parent().data('id');

                $.ajax({
                    url: '{% url 'games:remove_game' %}',  // replace with the actual URL of your delete view
                    method: 'POST',
                    data: {
                        'game_id': game_id,
                        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                    },
                    success: function(data) {
                        // Remove the game element from the DOM
                        $(this).parent().remove();
                    }.bind(this)
                });
            });
        });
    </script>
    {% endif %}
{% endblock %}

templates/authentication/signup.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="container text-center">
            <div class="row" style="padding-top: 10px; margin-top: 3%; text-align: left; border-bottom: 1px solid black; ">
                <div class="col">
                    <h1>Sign up</h1>
                </div>
            </div>
        </div>
        <div class="container" style="padding: 2%">
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="mb-3">
            <label for="password1" class="form-label">Password</label>
            <input type="password" class="form-control" id="password1" name="password1" required>
        </div>
        <div class="mb-3">
            <label for="password2" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="password2" name="password2" required>
        </div>
        <button type="submit" class="btn btn-primary">Sign Up</button>
        </div>
    </form>
</div>
{% endblock %}

templates/authentication/social.html
{% extends 'index.html' %}
{% block content %}
<div class="container text-center">
    <div class="row" style="padding-top: 10px; margin-top: 3%; text-align: left; border-bottom: 1px solid black; ">
        <div class="col">
            <h2>Social</h2>
        </div>
    </div>
</div>
    {% for user in users %}
        <li>
            <a href="{% url 'members:profile' user.username %}">
                <strong>{{ user.username }}</strong>
            </a>
        </li>
    {% endfor %}
{% endblock %}