games/urls.py
from django.urls import path
from members.views import profile_page
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'games'

urlpatterns = [
	path('add_game/', views.add_game, name='add_game'),
	path('add_game/<int:game_id>', views.add_game, name='add_game_with_id'),
	path('game_list/', views.game_list, name='game_list'),
	path('game_create/', views.game_create, name='game_create'),
	path('game_create/<int:suggestion_id>', views.game_create, name='game_create_with_suggestion'),
	path('game_suggestions/', views.game_suggestions, name='game_suggestions'),
	path('suggestion_create/', views.suggestion_create, name='suggestion_create'),
	path('remove_game/', views.remove_game, name='remove_game'),
	path('update_game_status/', views.update_game_status, name='update_game_status'),
	path('game/<int:game_id>/', views.game_detail, name='game_detail'),
	path('game/<int:game_id>/edit', views.edit_game, name='edit_game'),
	path('game/<int:game_id>/rate_game/<int:rating>', views.rate_game, name='rate_game'),
]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
	path('login_user', views.login_user, name='login'),
	path('logout_user', views.logout_user, name='logout'),
	path('signup_user', views.signup_user, name='signup'),
	path('profile/<str:username>', views.profile_page, name='profile'),
	path('social', views.social, name='social'),
	path('aboutus', views.aboutus, name='aboutus'),
]

pandalibrary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('games/', include('games.urls')),
    path('', index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Game(models.Model):
    STATUS_CHOICES = [
        ('PC', 'PC'),
        ('Playstation', 'Playstation'),
        ('Xbox', 'Xbox'),
        ('Mobile', 'Mobile'),
    ]
    title = models.CharField(max_length=100)
    developer = models.CharField(max_length=100)
    release_date = models.DateField(null=True, blank=True)
    platform = models.CharField(max_length=50, choices=STATUS_CHOICES, blank=True, null=True)
    genre = models.CharField(max_length=50, blank=True)
    description = models.TextField(blank=True)
    cover = models.ImageField(upload_to='covers', blank=True, null=True)
    average_rating = models.FloatField(default=0)
    hltb = models.CharField(max_length=100, blank=True)
    metacritic = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.title + ' by ' + self.developer


class Comment(models.Model):
    game = models.ForeignKey(Game, related_name="comments", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def str(self):
        return f"Comment by {self.user.username} on {self.game.title}"


class GameSuggestion(models.Model):
    title = models.CharField(max_length=100)
    suggested_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + ' suggested by ' + self.suggested_by.username

games/forms.py
from django import forms
from .models import Game, Comment


class GameForm(forms.ModelForm):
    class Meta:
        CHOICES = (
            ('PC', 'PC'),
            ('Playstation', 'Playstation'),
            ('Xbox', 'Xbox'),
            ('Mobile', 'Mobile'),
        )

        model = Game
        fields = ['title', 'developer', 'release_date', 'platform', 'genre', 'description', 'cover', 'hltb',
                  'metacritic']
        widgets = {
            'title': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'developer': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'release_date': forms.DateInput(attrs={'type': 'text', 'class': 'form-control'}),
            'platform': forms.Select(choices=CHOICES, attrs={'class': 'form-control'}),
            'genre': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'}),
            'description': forms.Textarea(attrs={'type': 'text', 'class': 'form-control'}),
            'cover': forms.FileInput(attrs={'type': 'file', 'class': 'form-control'}),
            'hltb': forms.URLInput(attrs={'type': 'url', 'class': 'form-control'}),
            'metacritic': forms.URLInput(attrs={'type': 'url', 'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(GameForm, self).__init__(*args, **kwargs)
        if 'initial' in kwargs:
            self.fields['title'].initial = kwargs['initial'].get('title')
        self.fields['title'].required = False
        self.fields['developer'].required = False
        self.fields['release_date'].required = False
        self.fields['platform'].required = False
        self.fields['genre'].required = False
        self.fields['description'].required = False
        self.fields['cover'].required = False
        self.fields['hltb'].required = False
        self.fields['metacritic'].required = False
        self.fields['hltb'].label = "How Long to Beat Page"
        self.fields['metacritic'].label = "Metacritic Page"


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment"]

        widgets = {
        'comment': forms.Textarea(attrs={'type': 'text', 'class': 'form-control'})
        }

class SuggestionsForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['title']
        widgets = {
            'title': forms.TextInput(attrs={'type': 'text', 'class': 'form-control'})
        }

games/views.py
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from members.forms import UserGamesForm
from members.models import UserGames
from .models import Game, Comment, GameSuggestion
from .forms import GameForm, CommentForm, SuggestionsForm
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect
from django.db import transaction


# Create your views here.
def game_list(request):
    games = Game.objects.all()
    return render(request, template_name='games/game_list.html', context={'games': games})


@login_required
def add_game(request, game_id=None):
    games = Game.objects.all()
    if request.method == 'POST':
        form = UserGamesForm(request.POST)
        if form.is_valid():
            user_game = form.save(commit=False)
            user_game.user = request.user
            if UserGames.objects.filter(user=user_game.user, game=user_game.game).exists():
                messages.error(request, 'This game is already added to your profile')
                return redirect('games:add_game')
            user_game.save()
            messages.success(request, 'Game has been added to your profile')
            return redirect('members:profile', username=request.user.username)
        else:
            messages.error(request, 'Error adding game to your profile. Please try again')
            return redirect('games:add_game')
    else:
        if game_id:
            game = get_object_or_404(Game, pk=game_id)
            form = UserGamesForm(initial={'game': game})
        else:
            form = UserGamesForm()

    return render(request, 'games/add_games.html', {'form': form, 'games': games})


def game_create(request, suggestion_id=None):
    if request.method == 'POST':
        form = GameForm(request.POST)
        if form.is_valid():
            title = request.POST.get('title')
            developer = request.POST.get('developer')
            release_date = request.POST.get('release_date')
            platform = request.POST.get('platform')
            genre = request.POST.get('genre')
            description = request.POST.get('description')
            cover = request.FILES.get('cover')
            game = Game(title=title, description=description,
                        developer=developer, release_date=release_date,
                        platform=platform, genre=genre, cover=cover)
            game.save()
            messages.success(request, 'Game has been created successfully')
            return redirect('games:game_list')
        else:
            print(form.errors)
            messages.error(request, 'Error creating game. Please try again')
            return redirect('games:game_create')
    else:
        if suggestion_id:
            suggestion = get_object_or_404(GameSuggestion, pk=suggestion_id)
            form = GameForm(initial={'title': suggestion.title})
            suggestion.delete()
        else:
            form = GameForm()
    return render(request, 'games/game_create.html', {'form': form})


def edit_game(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    if request.method == 'POST':
        form = GameForm(request.POST, request.FILES, instance=game)
        if 'action' in request.POST and request.POST['action'] == 'delete':
            game.delete()
            messages.success(request, 'Game has been deleted successfully')
            return redirect('games:game_list')
        if form.is_valid():
            form.save()
            messages.success(request, 'Game has been updated successfully')
            return redirect('games:game_list')
        else:
            messages.error(request, 'Error updating game. Please try again')
            return redirect('games:edit_game', game_id=game_id)
    else:
        form = GameForm(instance=game)
    return render(request, 'games/edit_game.html', {'form': form})


@login_required
@transaction.atomic
def update_game_status(request):
    if request.method == 'POST':
        game_id = request.POST.get('game_id')
        new_status = request.POST.get('status')
        user_game = get_object_or_404(UserGames, user=request.user, game_id=game_id)
        user_game.status = new_status
        user_game.save()
        return JsonResponse({'status': 'success'})
    else:
        return JsonResponse({'status': 'failed'})


@login_required
def remove_game(request):
    if request.method == 'POST':
        game_id = request.POST.get('game_id')
        UserGames.objects.filter(user=request.user, game_id=game_id).delete()
        return JsonResponse({'status': 'success'})
    else:
        return JsonResponse({'status': 'failed'})


def game_detail(request, game_id):
    game = get_object_or_404(Game, pk=game_id)
    comments = game.comments.all()
    new_comment = None
    star_range = range(5)
    if request.user.is_authenticated:
        user_has_game = UserGames.objects.filter(user=request.user, game=game).exists()
    else:
        user_has_game = False

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.user = request.user
            new_comment.game = game
            new_comment.save()
            return HttpResponseRedirect(reverse('games:game_detail', kwargs={'game_id': game.pk}))
    else:
        comment_form = CommentForm()

    return render(request, 'games/game_detail.html',
                  {'game': game,
                   'star_range': star_range,
                   'user_has_game': user_has_game,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form})


@login_required
@require_POST
def rate_game(request, game_id, rating):
    if request.method == 'POST':
        game = get_object_or_404(Game, pk=game_id)
        user_game = get_object_or_404(UserGames, user=request.user, game=game)
        user_game.rating = rating
        user_game.save()

        total = 0
        for object in UserGames.objects.filter(game=game):
            try:
                total += object.rating
            except:
                pass
        game.average_rating = total / UserGames.objects.filter(game=game).count()
        game.save()
        return JsonResponse({'average_rating': user_game.rating})


def game_suggestions(request):
    suggestions = GameSuggestion.objects.all()
    return render(request, 'games/game_suggestions.html', {'suggestions': suggestions})


def suggestion_create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        suggestion = GameSuggestion(title=title, suggested_by=request.user)
        suggestion.save()
        messages.success(request, 'Suggestion has been created successfully')
        return redirect('games:game_list')
    else:
        form = SuggestionsForm()
    return render(request, 'games/suggestion_create.html', {'form': form})

templates/games/add_games.html
{% extends 'index.html' %}
{% block additional_scripts %}
{% endblock %}
{% block content %}

<div class="container text-center">
    <div class="row" style="padding-top: 10px; margin-top: 3%; text-align: left; border-bottom: 1px solid black; ">
        <h2>Add Game</h2>
    </div>
</div>

<div class="container" style="margin-top: 20px;">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="game" class="form-label">Game</label>
            <select id="game" name="game" class="form-control">
                {% for game in games %}
                <option value="{{ game.id }}">{{ game.title }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <label for="status" class="form-label">Status</label>
            <select id="status" name="status" class="form-control">
                <option value="playing">Playing Now</option>
                <option value="will_play">Will Play</option>
                <option value="finished">Finished</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Add Game</button>
    </form>
</div>
{% endblock %}

templates/games/edit_game.html
{% extends 'index.html' %}
{% block content %}

<div class="container text-center">
    <div class="row" style="padding-top: 10px; margin-top: 3%; text-align: left; border-bottom: 1px solid black; ">
        <h2>Edit Game</h2>
    </div>
</div>

<div class="container" style="margin-top: 20px;">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary" style="margin-top: 20px">Edit Game</button>
        <button type="submit" name="action" value="delete" class="btn btn-primary" style="margin-top: 20px; margin-left: 1050px; border-color: darkred; background-color: darkred">Delete Game</button>
    </form>
</div>
{% endblock %}

templates/games/game_create.html
{% extends 'index.html' %}
{% block content %}

<div class="container text-center">
    <div class="row" style="padding-top: 10px; margin-top: 3%; text-align: left; border-bottom: 1px solid black; ">
        <h2>Create Game</h2>
    </div>
</div>

<div class="container" style="margin-top: 20px;">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">Title</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="{{ form.developer.id_for_label }}">Developer</label>
            {{ form.developer }}
        </div>
        <div class="form-group">
            <label for="{{ form.release_date.id_for_label }}">Release Date</label>
            {{ form.release_date }}
        </div>
        <div class="form-group">
            <label for="{{ form.platform.id_for_label }}">Platform</label>
            {{ form.platform }}
        </div>
        <div class="form-group">
            <label for="{{ form.genre.id_for_label }}">Genre</label>
            {{ form.genre }}
        </div>
        <div class="form-group">
            <label for="{{ form.description.id_for_label }}">Description</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="{{ form.cover.id_for_label }}">Cover</label>
            {{ form.cover }}
        </div>
        <div class="form-group">
            <label for="{{ form.metacritic.id_for_label }}">Metacritic Page Link</label>
            {{ form.metacritic }}
        </div>
        <div class="form-group">
            <label for="{{ form.hltb.id_for_label }}">How Long to Beat Page Link</label>
            {{ form.hltb}}
        </div>
        <button type="submit" class="btn btn-primary">Create Game</button>
    </form>
</div>
{% endblock %}

templates/games/game_detail.html
{% extends 'index.html '%}
{% load static %}

{% block content %}
<div class="container text-center">
    <div class="row" style="padding-top: 10px; margin-top: 3%; text-align: left; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);">
        <div class="col">
            <h2>{{ game.title }}</h2>
            <p>Released on: {% if game.release_date  %} {{game.release_date}} {% else %} Not yet {% endif %} <p></p>
        </div>
        <div class="col" style="text-align: right;">
            {% if user.is_superuser %}
                <p><a class="btn btn-primary btn-lg" href="{% url 'games:edit_game' game.id %}">Edit Game</a></p>
            {% endif %}
        </div>
    </div>
    <div class="row" style="padding: 2%; margin-top: 15px; text-align: left; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);">
        <div class="col">
            <img {% if game.cover %} src="{{ game.cover.url }}" {% else %} src="{% static 'game1.jpg' %}" {% endif %} class="card-img-top" alt="{{ game.title }}" style="width: 400px; height: 600px; object-fit: cover; border-radius: 10px">
        </div>
        <div class="col">
            <h3>Description</h3>
            <p>{{ game.description }}</p>
            <h3>Genre</h3>
            <p>{{ game.genre }}</p>
            <h3>Platform</h3>
            <p>{{ game.platform }}</p>
            <h3>Developer</h3>
            <p>{{ game.developer }}</p>
            <h3>Rating</h3>
            <div class="stars">
                {% for i in star_range %}
                    <i class="fas fa-star star" data-value="{{ i|add:1 }}"></i>
                {% endfor %}
                <p>Average rating: {{ game.average_rating }}</p>
            </div>
            {% if user.is_authenticated %}
                 <p><a href="{% url 'games:add_game_with_id' game.id %}" class="btn btn-primary">Add Game</a></p>
            {% endif %}
        </div>
      <div class="row">
        <div class="col" style="align-items: center; display: flex; padding-bottom: 10px; padding-top: 10px; margin-top: 3%; text-align: left; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);">
            <a href="{{ game.metacritic }}" style="color: inherit; text-decoration: none; display: flex; align-items: center;">
                <img src="{% static 'metacritic.png' %}" alt="Metacritic logo" class="logo">
                <h1>Metacritic Page</h1>
            </a>
        </div>
            <div class="col" style="align-items: center;  display: flex; padding-bottom: 10px; padding-top: 10px; margin-top: 3%; margin-left: 3%; text-align: left; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);">
                <a href="{{ game.hltb }}" style="color: inherit; text-decoration: none; display: flex; align-items: center;">
                    <img src="{% static 'hltb.png' %}" alt="Hltb logo" class="logo">
                    <h1>How Long to Beat Page</h1>
                </a>
            </div>
      </div>
    <div class="row">
        <div class="col" style="padding: 2%; margin-top: 15px; text-align: left; border: 1px solid black; border-radius: 10px; box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.5);">
            <h3>Comments</h3>
            <ul>
                {% for comment in comments %}
                    <li>
                        <strong>{{ comment.user.username }}</strong> ({{ comment.created_at }}): {{ comment.comment }}
                    </li>
                {% empty %}
                    <li>No comments yet.</li>
                {% endfor %}
            </ul>

            {% if user.is_authenticated %}
                <h3>Add a comment</h3>
                <form method="post">
                    {% csrf_token %}
                    {{ comment_form }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            {% else %}
                <p>You need to <a href="{% url 'members:login' %}">login</a> to add a comment.</p>
            {% endif %}
        </div>
    </div>
    </div>
</div>
{% endblock %}

{% block additional_scripts %}
<script>
    var stars = document.querySelectorAll('.star');
    var game_id = {{ game.id }};
    var user_authenticated = {{ user.is_authenticated|yesno:"true,false" }};
    stars.forEach(function(star) {
        star.addEventListener('mouseover', function() {
            var value = this.getAttribute('data-value');
            stars.forEach(function(star) {
                if (star.getAttribute('data-value')<= value) {
                    star.classList.add('hover');
                } else {
                    star.classList.remove('hover');
                }
            });
        });
        star.addEventListener('mouseout', function() {
            stars.forEach(function(star) {
                star.classList.remove('hover');
            });
        });
        star.addEventListener('click', function() {
            if (!user_authenticated) {
                alert('You must be logged in to rate a game.');
                window.location.href = "{% url 'members:login' %}";
                return;
            }
            if (!{{ user_has_game|yesno:"true,false" }}) {
                alert('You must have this game in your profile to rate it.');
                return;
            }
            var value = this.getAttribute('data-value');
            fetch('/games/game/' + game_id + '/rate_game/'+ value, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}'
                }
            })
            .then(response => response.json())
            .then(data => {
                var average_rating = data.average_rating;
                console.log("Average rating: " + average_rating);  // Add this line
                stars.forEach(function(star) {
                    var star_value = star.getAttribute('data-value');
                    console.log("Star value: " + star_value);  // Add this line
                    if (star_value <= average_rating) {
                        star.classList.add('rated');
                    } else {
                        star.classList.remove('rated');
                    }
                });
                location.reload()
                alert('Your rating has been saved!');
            });
        });
    });
</script>
{% endblock %}

{% block additional_styles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<style>
    .star {
    font-size: 20px;
    margin-right: 5px;
    color: #ccc;
    }

    .star.hover, .star.rated {
        color: orange;
    }
}
</style>
{% endblock %}

templates/games/game_list.html
{% extends 'index.html' %}
{% load static %}
{% block additional_styles %}
<style>
    .game-card {
    margin: 50px;
    }
    .game-card:hover{
    transform: scale(1.1);
    }
    .game-image {
    width: auto;
    height: 400px;
    object-fit: cover;
    }
</style>
{% endblock %}
{% block content %}

<div class="container text-center">
    <div class="row" style="padding-top: 10px; margin-top: 3%; text-align: left; border-bottom: 1px solid black; ">
        <div class="col">
            <h2>Games</h2>
        </div>
        {% if request.user.username == "admin" %}
        <div class="col" style="text-align: right">
        <p><a class="btn btn-primary btn-lg" href="{% url 'games:game_suggestions' %}" role="button">Show Suggestions</a></p>
            <p><a class="btn btn-primary btn-lg" href="{% url 'games:game_create' %}" role="button">Create One</a></p>
        </div>
        {% elif user.is_authenticated %}
        <div class="col" style="text-align: right">
            <p><a class="btn btn-primary btn-lg" href="{% url 'games:suggestion_create' %}" role="button">Suggest One</a></p>
        </div>
        {% endif %}
    </div>
</div>
<div class="container">
    <div class="row">
        {% for game in games %}
        <div class="col-md-2 game-card" id="game-{{ game.pk }}">
            <a href="{% url 'games:game_detail' game.pk %}" style="color: inherit; text-decoration: none;">
                <div class="card" style="width: 18rem;">
                    {% if game.cover %}
                    <img src="{{ game.cover.url }}" class="card-img-top game-image" alt="{{ game.title }}">
                    {% else %}
                    <img src="{% static 'game1.jpg' %}" class="card-img-top game-image" alt="{{ game.title }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ game.title }}</h5>
                    </div>
                </div>
            </a>
        </div>
        {% if forloop.counter|divisibleby:4 %}
        </div>
        <div class="row">
        {% endif %}
        {% empty %}
        <p>No games available.</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/games/game_suggestions.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
    <h1>Game Suggestions</h1>
    <ul>
        {% for suggestion in suggestions %}
        <li>
            <a href="{% url 'games:game_create_with_suggestion' suggestion.id %}">{{ suggestion.title }}</a> suggested by {{ suggestion.suggested_by.username }}
        </li>
        {% empty %}
        <li>No game suggestions.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/games/suggestion_create.html
{% extends 'index.html' %}

{% block content %}
<div class="container text-center">
    <div class="row" style="padding-top: 10px; margin-top: 3%; text-align: left; border-bottom: 1px solid black; ">
        <h2>Suggest Game</h2>
    </div>
</div>

<div class="container" style="margin-top: 20px;">
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary">Suggest Game</button>
    </form>
</div>
{% endblock %}