games/urls.py
from django.urls import path
from members.views import profile_page
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'games'

urlpatterns = [
	path('add_game/', views.add_game, name='add_game'),
	path('add_game/<int:game_id>', views.add_game, name='add_game_with_id'),
	path('game_list/', views.game_list, name='game_list'),
	path('game_create/', views.game_create, name='game_create'),
	path('game_create/<int:suggestion_id>', views.game_create, name='game_create_with_suggestion'),
	path('game_suggestions/', views.game_suggestions, name='game_suggestions'),
	path('suggestion_create/', views.suggestion_create, name='suggestion_create'),
	path('remove_game/', views.remove_game, name='remove_game'),
	path('update_game_status/', views.update_game_status, name='update_game_status'),
	path('game/<int:game_id>/', views.game_detail, name='game_detail'),
	path('game/<int:game_id>/edit', views.edit_game, name='edit_game'),
	path('game/<int:game_id>/rate_game/<int:rating>', views.rate_game, name='rate_game'),
]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
	path('login_user', views.login_user, name='login'),
	path('logout_user', views.logout_user, name='logout'),
	path('signup_user', views.signup_user, name='signup'),
	path('profile/<str:username>', views.profile_page, name='profile'),
	path('social', views.social, name='social'),
	path('aboutus', views.aboutus, name='aboutus'),
]

pandalibrary/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('games/', include('games.urls')),
    path('', index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/index.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous">
<style>
    .logo {
    width: 75px;
    height: 75px;
}
</style>
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Pandalibrary</title>
    <link rel="icon" href="{% static 'pandalogo.png' %}">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark" style="font-size: 20px">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
    <img src="{% static 'pandalogo.png' %}" alt="pandalogo" class="logo">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link {% if request.path == '/games/game_list' %}active{% endif %}" href="{% url 'games:game_list' %}">Games</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if request.path == '/games/game_list' %}active{% endif %}" href="{% url 'members:aboutus' %}">About Us</a>
        </li>
      </ul>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/members/login_user' %}active{% endif %}"
                 href="{% url 'members:social' %}">Social</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" >
                  {{ request.user.username }}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'members:profile' request.user.username %}">Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'members:logout' %}">Log out</a></li>
                </ul>
            </li>
        {% else %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/members/login_user' %}active{% endif %}"
                 href="{% url 'members:login' %}">Log in</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/members/signup_user' %}active{% endif %}"
                 href="{% url 'members:signup' %}">Sign Up</a>
            </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
    <div class="container mt-3">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-{% if message.tags == 'error' %}warning{% else %}{{ message.tags }}{% endif %}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% if request.path == '/' %}
    <video class="video-bg" autoplay muted loop>
        <source src="{% static 'frostpunk2.mp4' %}" type="video/mp4">
        Your browser does not support the video tag.
    </video>
{% endif %}
<div class="container">
    {% block content %}
         <p class="text-center fs-1">Welcome to PandaLibrary</p>
    <h2 class="text-center mt-4">Highest Rating</h2>
    <div id="gameCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="row">
              {% for game in highest_rates %}
                <div class="col-3">
                    <a href="{% url 'games:game_detail' game.id %}" style="color: inherit; text-decoration: none; display: flex; align-items: center;">
                    <img {% if game.cover %} src="{{ game.cover.url }}" {% else %} src="{% static 'game1.jpg' %}" {% endif %} class="card-img-top" alt="{{ game.title }}" style="width: 300px; height: 450px; object-fit: cover; border-radius: 10px">
                    </a>
                </div>
              {% endfor %}
          </div>
        </div>
    </div>

    <h2 class="text-center mt-4">Latest Releases</h2>
    <div id="gameCarousel2" class="carousel slide">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="row">
            {% for game in latest_releases %}
                <div class="col-3">
                    <a href="{% url 'games:game_detail' game.id %}" style="color: inherit; text-decoration: none; display: flex; align-items: center;">
                    <img {% if game.cover %} src="{{ game.cover.url }}" {% else %} src="{% static 'game1.jpg' %}" {% endif %} class="card-img-top" alt="{{ game.title }}" style="width: 300px; height: 450px; object-fit: cover; border-radius: 10px">
                    </a>
                </div>
              {% endfor %}
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
    {% block additional_styles %}{% endblock %}
    {% block additional_scripts %}{% endblock %}
</div>
</body>
</html>